from django.conf import settings

DJANGO_REVIEWS = getattr(settings, "DJANGO_REVIEWS", {})

# TODO: import settings from django settings
MAX_SCORE = DJANGO_REVIEWS.get('MAX_SCORE', 5)
MIN_SCORE = DJANGO_REVIEWS.get('MIN_SCORE', 1)
SCORE_CHOICES = DJANGO_REVIEWS.get('SCORE_CHOICES', zip(
    range(MIN_SCORE, MAX_SCORE + 1),
    range(MIN_SCORE, MAX_SCORE + 1)
))
MAX_COMMENT_LENGTH = DJANGO_REVIEWS.get('MAX_COMMENT_LENGTH', 1000)
UPDATED_COMPARISON_SECONDS = DJANGO_REVIEWS.get('UPDATED_COMPARISON_SECONDS', 10)
AVG_SCORE_DIGITS = DJANGO_REVIEWS.get('AVG_SCORE_DIGITS', 2)
